library(doParallel)
library(BuenColors)
library(FigR)
library(BSgenome.Hsapiens.UCSC.hg38)
library(ggplot2)
library(ComplexHeatmap)
library(networkD3)
require(htmlwidgets)
library(cowplot)
library(ggrepel)
library(patchwork)
library(pheatmap)
library(RColorBrewer)
library(viridis)
## type1
figR.d<-readRDS("./output/type1.figR.d.rds")
rankDrivers(figR.d,rankBy = "meanScore")
rankDrivers_gene<-rankDrivers(figR.d,rankBy = "meanScore")
write.csv(rankDrivers_gene$data,"./output/type1.rankDrivers.csv",row.names=T)
## type2
figR.d<-readRDS("./output/type2.figR.d.rds")
rankDrivers(figR.d,rankBy = "meanScore")
rankDrivers_gene<-rankDrivers(figR.d,rankBy = "meanScore")
write.csv(rankDrivers_gene$data,"./output/type2.rankDrivers.csv",row.names=T)
